package.json

Will need to be released after merging this.

Update gamification-engine dependency

---

lib/comment.js
lib/share.js
lib/user.js
lib/util/urls.js

- Create a util function to create avatar urls
- Expand all received data containing user id by adding avatar
- Update dates from comments to match local user date

Normalize avatars and dates

---

lib/user.js

Await completion of all image uploads before returning response.

Image upload res

---

README.md
index.js
lib/account.js
lib/client.js
lib/comment.js
lib/gamification.js
lib/ping.js
lib/response-cache.js
lib/share.js
lib/user.js
package.json
plugins/offline-gamification.js

* afterData renamed to afterDataProcessed
* afterSuccess renamed to afterDataProcessed for consistency
* afterDataProcessed and afterDataReceived both receive endpoint as first param
* added afterDataReceived that receives raw API response
* added ResponseCache
Contains breaking changes.

Refactoring afterData hook

---

lib/user.js
package.json
yarn.lock

To be merged after https://github.com/KanoComputing/gamification-engine/pull/58 has been released.

Avatar + rewards changes

---

lib/user.js
lib/util/urls.js
package.json

To avoid having to do `s/head.png/full.png/`.

expandUser: Add separate avatarFull URL

---

Jenkinsfile
package.json
yarn.lock

Also bump to 3.3.3 so we can release.

Updating gamification-engine dependency to NPM

---

.npmignore
Jenkinsfile
yarn.lock

- Update Jenkinsfile to use docker containers
- Add items to .npmignore

SX-311 Update CI

---

package.json
yarn.lock

Depends on: https://github.com/KanoComputing/gamification-engine/pull/72

Bump gamification-client

---

lib/account.js

The forgot username and password do not send back JSON data

Use correct response type

---

lib/client.js
lib/ping.js
package.json
plugins/gamification-fallback.js

This was making the app connection detection think that the API was unavailable because of the failing requests.

Bypass the API when using gamification anonymously

---

lib/account.js

* These all return 404 at the moment - waiting to check with services team.

SX-1199 consent 

---

lib/account.js
lib/user.js

• added `getDeleteAccountAuth`, `deleteAccount ` & `getUserSettings `

Settings page endpoints

---

package.json
yarn.lock

Adds basic Star Wars challenges

Update gamification to 2.5.3

---

lib/user.js

- Add /users/me support with optional token (Can be provided through a plugin or explicitely)

feat(user): Add /users/me endpoint

---

lib/task.js

- Add the missing delete account task

feat: add delete account task

---

lib/account.js

feat: add marketingEnabled endpoint

---

lib/share.js

- Send the parent key to the API

feat: track the parent of a creation

---

package.json
plugins/gamification-fallback.js
yarn.lock

- Remove the dependency to gamification-engine
- Accepts the gamification module as a parameter

Gamification injected

---

lib/account.js

To be used in kit-app-ui to refresh login sessions (and to log people out when we delete their accounts).
#coppa

feat: Adding GET /accounts/auth/refresh

---

lib/share.js

- Add the moderation step inside the create method

feat: Add moderation trigger

---

lib/account.js

Support guardian endpoints

---

lib/client.js
lib/share.js
lib/user.js
package.json
yarn.lock

This library uses fetch, which is a web api, but it would be convenient to use it for testing as well.
This PR imports cross-fetch, which multiplexes between node-fetch and the web-api fetch, allowing the library to be used in node.
It seems to work in Node.

Use fetch via cross-fetch.

---

package.json

Bump version for release.
